baseURL = 'https://icst-ambisonics.github.io/'
languageCode = 'en-us'
title = 'The ICST Ambisonics Site'
theme = 'anatole'
enableEmoji = true

[params]
title = "The ICST Ambisonics"
author = "Johannes Schuett"
singleDateFormat = "2006-01-02"
description = " This is the ICST Ambisonics Tutorial Blog"
profilePicture = "image/AmbiPlugin_logo.gif"
mainSections = ["blog"]
favicon = "favicons/"

    
## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/jschuett"

## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/HOME/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "ICST Ambisonics Plugins"
  weight = 300
  identifier = "ICST Ambisonics Plugins"
  url = "/ICST Ambisonics Plugins/"

  [[menu.main]]
  name = "ICST Ambisonics Tools"
  weight = 400
  identifier = "ICST Ambisonics Tools"
  url = "/ICST Ambisonics Tools/"
  
  [[menu.main]]
  name = "Tutorials"
  weight = 400
  identifier = "Tutorials"
  url = "/Tutorials/"
  

  [[menu.main]]
  name = "Links"
  weight = 500
  identifier = "Links"
  url = "/Links/"

  [[menu.main]]
  name = "About"
  weight = 600
  url = "/about/"

  [[menu.footer]]
  name = "License"
  weight = 1
  identifier = "License"
  url = "/License.md/"

[taxonomies]
series = "series"
tag = "tags"


