baseURL = 'https://ambisonics.ch/'
languageCode = 'en-us'
title = 'The ICST Ambisonics Site'
theme = 'anatole'
enableEmoji = true
buildFuture = true

[params]
title = "ICST Ambisonics"
authorName = "Johannes Schuett"
email = "johannes.schuett@zhdk.ch"
rssFullContent = true
singleDateFormat = "2006-01-02"
description = "Spatial Audio Plugins & Tutorials\nby ICST · Zurich University of the Arts"
profilePicture = "images/AmbiPlugin_logo.gif"
mainSections = ["blog", "post"]
favicon = "favicons/"
contentratio = 0.7
copyright = "Johannes Schuett {{ YEAR }}"

  [params.author]
  name  = "Johannes Schuett"
  email = "johannes.schuett@zhdk.ch"

[markup.goldmark.renderer]
unsafe = true
ignoreLogs = ["warning-goldmark-raw-html"]

## Social links
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/joambi"


## Menu items
[menu]

  [[menu.main]]
  name = "Plugins & Tools"
  identifier = "docs"
  weight = 100
  url = "#"

    [[menu.main]]
    name = "Plugin Docs"
    parent = "docs"
    weight = 101
    url = "/ICST Ambisonics Plugins/"

    [[menu.main]]
    name = "Ambi Tools"
    parent = "docs"
    weight = 102
    url = "/ICST Ambisonics Tools/"

  [[menu.main]]
  name = "Tutorials"
  identifier = "tutorials"
  weight = 200
  url = "/post/"

  [[menu.main]]
  name = "ASCOLTA"
  identifier = "ascolta"
  weight = 250
  url = "/blog/ascolta/"

  [[menu.main]]
  name = "Residenzen"
  identifier = "residenzen"
  weight = 300
  url = "/residenzen/"

  [[menu.main]]
  name = "Studio"
  identifier = "blog"
  weight = 350
  url = "/blog/"

  [[menu.main]]
  name = "Links"
  identifier = "links"
  weight = 400
  url = "/Links/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 500
  url = "/about/"

  [[menu.footer]]
  name = "Privacy Policy"
  weight = 1
  identifier = "Privacy Policy"
  url = "https://www.iubenda.com/privacy-policy/70769495/full-legal"


[taxonomies]
series = "series"
tag = "tags"
year = "year"
month = "month"
