[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.159.1"
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://ambisonics.ch"

[[headers]]
  for = "/*"
    [headers.values]
      Access-Control-Allow-Origin = "*"
