name: update resources

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: install dart sass
        run: |
          DART_SASS_VERSION="1.89.0"
          wget -q https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz
          tar -xf dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz
          sudo mv dart-sass/sass /usr/local/bin/
          rm -rf dart-sass dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz
      - name: setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          extended: true
          hugo-version: 0.147.9
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install
        run: |
          npm ci
          npm run prepare
      - name: clean resources
        run: |
          rm -rf resources/* exampleSite/resources/*
      - name: build
        run: npm run build
      - name: commit resources
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: 'chore: build resources'
          file_pattern: resources/** exampleSite/resources/**
